# Generated by Django 3.0.4 on 2020-03-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuizWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=64)),
                ('foreign', models.CharField(max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Language')),
            ],
        ),
    ]
