# Generated by Django 3.0.4 on 2020-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200330_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='emoji',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
