# Generated by Django 3.0.4 on 2020-03-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_language_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
