# Generated by Django 3.0.4 on 2020-03-31 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200330_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizword',
            options={'ordering': ('english',)},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='japan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizword',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
